### PR TITLE
rootfs: Adjust for gendrv

### PR DESCRIPTION
**Pull request by vchong**
Signed-off-by: Victor Chong victor.chong@linaro.org

### CODE REVIEW

**Comment by jockebech** [comment]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by jforissier** [comment]
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by vchong** [comment]
Depends on https://github.com/OP-TEE/build/pull/62.

**Comment by vchong** [comment]
Tags added and ready for merge.
Thanks!

**Pull request merged**
