### PR TITLE
rootfs: Adjust for gendrv

### PR DESCRIPTION
**Pull request by vchong**
Signed-off-by: Victor Chong victor.chong@linaro.org

### CODE REVIEW

**Comment by vchong** [comment]
Same PR to both master and gendrv branches as there are no differences between both, but some manifests are still pointing to gendrv branch.

**Comment by pascal-brand38** [comment]
Should not we change the manifest to point to master branch only, and make branch gendrv obsolete?

**Comment by vchong** [comment]
Agree. Will cancel this and submit PR for manifest.
Thanks!

**Comment by vchong** [comment]
https://github.com/OP-TEE/manifest/pull/28 submitted.

**Pull request closed without merging**
