### PR TITLE
Remove things already taken care of in build.git - take 2

### PR DESCRIPTION
**Pull request by vchong**
Triggered by https://github.com/OP-TEE/build/pull/108

Signed-off-by: Victor Chong <victor.chong@linaro.org>

### CODE REVIEW

**Comment by jforissier** [comment]
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by vchong** [comment]
Tag added. Please merge if ok. Thanks!

**Comment by jforissier** [comment]
Actually I do have a couple of comments ;)
- You should remove `rootfs/init.d.optee` since it's not used anymore
- The commit message looks weird to me. Why "take 2"? I suppose we don't care once it's committed. And instead of saying "Remove things", say what you're removing, e.g., "Remove optee startup script since it's taken care of in build.git" (please keep the link to the build.git PR, it's fine).

**Comment by vchong** [comment]
> You should remove rootfs/init.d.optee since it's not used anymore

Ok.

> Why "take 2"?

Because the latest commit in this repo is 'Remove things already taken care of in build.git'. :s I'll change it.

**Comment by vchong** [comment]
Comments addressed.

**Pull request merged**
